# RECUERDEN NO IGNORAR ESTE ARCHIVO, O NO LES PODREMOS CORREGIR.
POPULARIDAD_MINIMA_DELEGACION = 0
PROBABILIDAD_ACCIDENTARSE_GIMNASIA = 0.3
# COMPLETAR...

INICIADOR_LOOP = True
NIVEL_IMPLEMENTOS = 0
MORAL_MINIMA = 20
DIAS_COMPETENCIA = 6

#### ENTRENAR ####
COSTO_ENTRENAR = 30
PUNTOS_ENTRENAMIENTO = 12
BONIFICACION_IEE =  1.7



# PONDERADORES/PARAMETROS PARA CALCULAR LOS GANADORES
PUNTAJE_MINIMO = 0
PONDERADOR_ATLETISMO_VELOCIDAD = 0.55
PONDERADOR_ATLETISMO_RESISTENCIA = 0.2
PONDERADOR_ATLETISMO_MORAL = 0.25

PONDERADOR_CICLISMO_VELOCIDAD = 0.47
PONDERADOR_CICLISMO_RESISTENCIA = 0.36
PONDERADOR_CICLISMO_FLEXIBIDAD = 0.17

PONDERADOR_GIMNASIA_FLEXIBILIDAD = 0.5
PONDERADOR_GIMNASIA_RESISTENCIA = 0.3
PONDERADOR_GIMNASIA_MORAL = 0.2

PONDERADOR_NATACION_FLEXIBILIDAD = 0.25
PONDERADOR_NATACION_RESISTENCIA = 0.3
PONDERADOR_NATACION_VELOCIDAD = 0.45

BONIFICACION_DCC = 2